version: 0.1-{build}
image: Visual Studio 2015
configuration: Debug
platform:
  - Win32
  - x64
before_build:
  - mkdir CMakeBuild
  - cd CMakeBuild
  - if %platform%==Win32 set CMAKE_GENERATOR=Visual Studio 9 2008
  - if %platform%==x64 set CMAKE_GENERATOR=Visual Studio 9 2008 Win64
  - cmake -G"%CMAKE_GENERATOR%" ..
  - cmake --build .
build: off
test_script:
  - ctest -V -C "Debug"
