version: build-{build}
image: Visual Studio 2017
configuration: Debug
platform:
  - Win32
  - x64
before_build:
  - mkdir CMakeBuild
  - cd CMakeBuild
  - if %platform%==Win32 set CMAKE_GENERATOR=Visual Studio 15 2017
  - if %platform%==x64 set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
  - cmake -G"%CMAKE_GENERATOR%" ..
build_script:
  - cmake --build .
test_script:
  - ctest -V -C "Debug"
